general {
    # Gaps and border
    gaps_in = 4
    gaps_out = 9
    gaps_workspaces = 50

    border_size = 3
    col.active_border = rgba(3c3c3caa)
    col.inactive_border = rgba(191919aa)
    resize_on_border = true

    no_focus_fallback = true

    allow_tearing = false # This just allows the `immediate` window rule to work

    snap {
        enabled = true
        window_gap = 4
        monitor_gap = 5
        respect_gaps = true
    }
}

dwindle {
    preserve_split = true
    smart_split = false
    smart_resizing = false
    # precise_mouse_move = true
}

decoration {
    # 2 = circle, higher = squircle, 4 = very obvious squircle
    # Clear squircles look really off; we use only extra .4 here to make the rounding feel more continuous
    rounding_power = 4
    rounding = 15

    # Change transparency of focused and unfocused windows
    #active_opacity = 0.9
    #inactive_opacity = 0.9

    blur {
        enabled = true
        xray = false
        special = false
        new_optimizations = true
        size = 10
        passes = 1
        brightness = 0.8
        noise = 0.05
        contrast = 1.15
        vibrancy = 1
        vibrancy_darkness = 1
        popups = true
        popups_ignorealpha = 0.6
        input_methods = true
        input_methods_ignorealpha = 0.8
    }

    shadow {
        enabled = true
        range = 5
        offset = 0 0
        render_power = 3
        color = rgba(1a1a1aee)
    }

    # Dim
    dim_inactive = true
    dim_strength = 0.05
    dim_special = 0.07
}

