# vim:ft=kitty

## Matugen - Material You dynamic theme

# The basic colors
foreground              #e7e1df
background              #141312
selection_background    #4c4640
selection_foreground    #e9ded7

# Cursor colors
cursor                  #e7e1df
cursor_text_color       #141312

# URL color
url_color               #c3c6d0

# The basic 16 colors
# black
color0  #141312
color8  #4d453f

# red
color1  #ffb4ab
color9  #93000a

# green
color2  #c3c6d0
color10 #3b3f47

# yellow
color3  #cec5bd
color11 #4c4640

# blue
color4  #d4c4b5
color12 #483d32

# magenta
color5  #c3c6d0
color13 #4c4640

# cyan
color6  #cec5bd
color14 #43474f

# white
color7  #e7e1df
color15 #d0c4bb

# Tab bar
active_tab_foreground   #392f24
active_tab_background   #d4c4b5
inactive_tab_foreground #e2d1c1
inactive_tab_background #483d32

# Window borders
active_border_color     #d4c4b5
inactive_border_color   #998f87
